version: '3.8'

services:
  teste-ambiente:
    image: python:3.10-slim
    volumes:
      - .:/app
    working_dir: /app
    command: python -c "print('Docker e Python estão integrados e funcionando!')"